#!/usr/bin/env python3
"""
Sync RaceLink WebUI screenshots into the docs repo and report which
ones still need an article.

The **canonical** screenshots are generated by the ``RaceLink_Host``
screenshot generator, which writes ``docs/screenshots/*.png`` plus a
``manifest.json`` (``name`` -> ``file`` -> ``description``) and a
``ui_build.hash``. This script mirrors those PNGs into this repo's
``docs/assets/screenshots/`` and then analyses coverage: every shot in
the manifest should be embedded in at least one docs page, otherwise it
is flagged as needing an article.

What it does
------------

1. **Sync** - copy new/changed ``*.png`` from the source into
   ``docs/assets/screenshots/`` (``manifest.json`` / ``ui_build.hash``
   are not copied). With ``--prune`` it also deletes dest PNGs that are
   no longer in the source.
2. **Analyse** - cross-reference the manifest against every
   ``docs/**/*.md`` file and report:
   * **NEEDS ARTICLE** - manifest shots not referenced by any page
     (a new screenshot you still have to write about / embed).
   * **ORPHAN** - PNGs in the dest folder that are neither in the
     manifest nor referenced (stale captures to delete).
   * **MISSING FILE** - a manifest entry whose PNG isn't on disk.

Usage
-----

.. code-block:: powershell

    # Sync + prune + coverage report (the normal "refresh docs" run):
    py scripts\\sync_screenshots.py --prune

    # Read-only: show what would change and the coverage report (CI):
    py scripts\\sync_screenshots.py --check

    # Custom source location (defaults to the sibling host repo):
    py scripts\\sync_screenshots.py --source ..\\RaceLink_Host\\docs\\screenshots

Exit code is non-zero when ``--check`` finds anything to do (a pending
sync, an unreferenced shot, an orphan, or a missing file) so it can
gate CI.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

# This script lives in <repo>/scripts/.
REPO_ROOT = Path(__file__).resolve().parent.parent
DEST_DIR = REPO_ROOT / "docs" / "assets" / "screenshots"
DOCS_DIR = REPO_ROOT / "docs"
DEFAULT_SOURCE = REPO_ROOT.parent / "RaceLink_Host" / "docs" / "screenshots"

# Files in the source folder that are sidecar metadata, not screenshots.
NON_IMAGE_NAMES = {"manifest.json", "ui_build.hash"}
# Files in the dest folder that are not screenshots and must be kept.
DEST_KEEP = {"README.md"}


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _load_manifest(source: Path) -> list[dict]:
    """Return the manifest 'shots' list, or [] if there is no manifest."""
    manifest = source / "manifest.json"
    if not manifest.is_file():
        return []
    data = json.loads(manifest.read_text(encoding="utf-8"))
    return data.get("shots", [])


def _md_reference_index() -> dict[str, list[str]]:
    """Map each referenced PNG basename -> list of docs pages that use it.

    Scans every ``docs/**/*.md`` (the screenshots README is excluded -
    it documents the folder, it doesn't 'use' the images)."""
    index: dict[str, list[str]] = {}
    png_ref = re.compile(r"([A-Za-z0-9_./-]+?\.png)")
    for md in DOCS_DIR.rglob("*.md"):
        rel = md.relative_to(REPO_ROOT).as_posix()
        if rel == "docs/assets/screenshots/README.md":
            continue
        text = md.read_text(encoding="utf-8")
        for match in png_ref.findall(text):
            name = Path(match).name
            index.setdefault(name, []).append(rel)
    return index


def sync(source: Path, *, prune: bool, check: bool) -> bool:
    """Mirror PNGs source -> dest. Returns True if anything changed (or,
    in check mode, *would* change)."""
    if not source.is_dir():
        sys.exit(f"error: source screenshots dir not found: {source}")

    DEST_DIR.mkdir(parents=True, exist_ok=True)

    src_pngs = {p.name: p for p in source.glob("*.png")}
    dest_pngs = {p.name: p for p in DEST_DIR.glob("*.png")}

    added, updated, removed = [], [], []

    for name, sp in sorted(src_pngs.items()):
        if name in NON_IMAGE_NAMES:
            continue
        dp = DEST_DIR / name
        if not dp.exists():
            added.append(name)
            if not check:
                dp.write_bytes(sp.read_bytes())
        elif _sha256(sp) != _sha256(dp):
            updated.append(name)
            if not check:
                dp.write_bytes(sp.read_bytes())

    for name in sorted(dest_pngs):
        if name in DEST_KEEP:
            continue
        if name not in src_pngs:
            removed.append(name)
            if prune and not check:
                (DEST_DIR / name).unlink()

    verb = "would add" if check else "added"
    if added:
        print(f"  + {verb} ({len(added)}): " + ", ".join(added))
    verb = "would update" if check else "updated"
    if updated:
        print(f"  ~ {verb} ({len(updated)}): " + ", ".join(updated))
    if removed:
        if prune:
            verb = "would delete" if check else "deleted"
            print(f"  - {verb} ({len(removed)}): " + ", ".join(removed))
        else:
            print(
                f"  ! {len(removed)} dest PNG(s) not in source "
                f"(pass --prune to delete): " + ", ".join(removed)
            )
    if not (added or updated or removed):
        print("  screenshots already in sync.")

    # In check mode, 'removed' counts as a pending change only with --prune;
    # without --prune it's a standing warning we still want surfaced.
    return bool(added or updated or removed)


def analyse(source: Path) -> bool:
    """Report coverage. Returns True if anything needs attention."""
    shots = _load_manifest(source)
    refs = _md_reference_index()
    referenced = set(refs)
    dest_pngs = {p.name for p in DEST_DIR.glob("*.png")}

    needs_article: list[tuple[str, str]] = []
    missing_file: list[str] = []
    manifest_files: set[str] = set()

    for shot in shots:
        fname = shot.get("file") or f"{shot.get('name', '?')}.png"
        manifest_files.add(fname)
        if not (DEST_DIR / fname).exists():
            missing_file.append(fname)
        if fname not in referenced:
            needs_article.append((fname, shot.get("description", "")))

    # If there is no manifest, fall back to "every dest PNG should be
    # referenced" so the coverage check still works.
    if not shots:
        for name in sorted(dest_pngs):
            if name not in referenced:
                needs_article.append((name, "(no manifest description)"))

    orphans = sorted(
        n for n in dest_pngs
        if n not in referenced and (not shots or n not in manifest_files)
    )

    print("\nCoverage report")
    print("---------------")
    if shots:
        covered = len(manifest_files) - len(
            [f for f, _ in needs_article if f in manifest_files]
        )
        print(f"  manifest shots: {len(shots)}  |  embedded in docs: {covered}")
    print(f"  dest PNGs: {len(dest_pngs)}  |  referenced by a page: "
          f"{len(dest_pngs & referenced)}")

    if needs_article:
        print(f"\nNEEDS ARTICLE - {len(needs_article)} screenshot(s) not "
              f"embedded in any page:")
        for fname, desc in needs_article:
            suffix = f"  - {desc}" if desc else ""
            print(f"  * {fname}{suffix}")

    if missing_file:
        print(f"\nMISSING FILE - {len(missing_file)} manifest shot(s) with "
              f"no PNG on disk (run a sync):")
        for fname in missing_file:
            print(f"  * {fname}")

    if orphans:
        print(f"\nORPHAN - {len(orphans)} dest PNG(s) neither in the manifest "
              f"nor referenced (consider deleting):")
        for name in orphans:
            print(f"  * {name}")

    if not (needs_article or missing_file or orphans):
        print("\n  OK: every screenshot is accounted for and embedded.")

    return bool(needs_article or missing_file or orphans)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", type=Path, default=DEFAULT_SOURCE,
                    help=f"source screenshots dir (default: {DEFAULT_SOURCE})")
    ap.add_argument("--prune", action="store_true",
                    help="delete dest PNGs that are no longer in the source")
    ap.add_argument("--check", action="store_true",
                    help="read-only: report what would change + coverage; "
                         "non-zero exit if anything needs doing (for CI)")
    args = ap.parse_args()

    source = args.source.resolve()
    print(f"Source: {source}")
    print(f"Dest:   {DEST_DIR.relative_to(REPO_ROOT)}\n")

    changed = sync(source, prune=args.prune, check=args.check)
    needs = analyse(source)

    if args.check and (changed or needs):
        print("\n--check: changes pending or coverage gaps - see above.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
